### ISSUE TITLE
绕不开的兼容性(持续完善)

### ISSUE THREAD

**Issue by vincenthou** [vincenthou/vincenthou.github.io#28]
# 背景

随着浏览器的发展，操作系统的更新升级，越来越多的用户开始使用现代浏览器，我们可喜的看见chrome浏览器在国外市场上高歌猛进
！[全球浏览器份额](http://imgsrc.baidu.com/forum/pic/item/095457fbb2fb43169fbd412022a4462308f7d387.jpg)
但是我们还是要面对现实，国内使用IE6, IE7, IE8这些浏览器的用户还是大有人在的
看看最新的统计数据：
[百度统计](http://tongji.baidu.com/data/browser)
[CNZZ统计](http://brow.data.cnzz.com/)
IE内核的浏览器还是大行其道的，所以就一些常见的兼容性问题做一下总结
# CSS兼容性

CSS兼容性问题应该是平时开发中最常碰见，也是最令人头疼的问题了，这里重点总结一下，首先有一个原则：浏览器的bug是有的，
但是并不像我们自已认为的那么常见，大部分问题是我们对于CSS规范理解的不完整，一般情况下我们优先考虑是不是自己的问题，如
果确定不是自己的问题，在从浏览器的bug方面入手突破。
## 渲染模式控制

[](http://www.mangguo.org/compatibility-mode-to-talk-about-x-ua-compatible/)
## CSS hack

为了获得统一的页面效果，就需要针对不同的浏览器或不同版本写特定的CSS样式，我们把这个针对不同的浏览器/不同版本写相应的CSS code的过程，叫做[CSS hack](http://blog.csdn.net/freshlover/article/details/12132801)

``` css
.all IE{property:value\9;}
.IE 9{property:value\9\0;}
.gte IE 8{property:value\0;}
.lte IE 7{*property:value;}
.IE 7{+property:value;}
.IE 6{_property:value;}
```
## 常见问题和方案
- 最好使用一些预检查工具（在线或者和开发工具集成的），帮助排除语法错误。
- 避免使用更特殊的选择器，遇到问题时候从根源上入手，而不是通过添加更加特殊的选择器，尽可能一般化，只有在细粒度的地方添加更特殊的选择器
- 垂直外边距叠加是一个有趣的现象，例如下面的代码

``` css
.wrap {
    margin: 10px;
    /*border: 1px solid black;*/
    /*padding: 1px;*/
    background-color: red;
}
.text {
    margin: 20px;
    background-color: yellow;
}
```

``` html
<div class="wrap">
    <p class="text">Test</p>
</div>
```

如果没有使用CSS代码中注释掉的部分，默认渲染的行为是在wrap的外层产生20px的margin而不是10。这是由具有块级子元素的元素计算高度方式造成的。
如果元素没有垂直的边框和内边距，那么它的高度就是包含的子元素内容的高度。解决的方法是去掉上面CSS代码中的任一条注释，添加边框或者是那边距。
通过chrome的开发调试工具的layout工具可以方便的调试盒模型
[CSS兼容性大全](http://wenku.baidu.com/link?url=fPsZEQjjFe8RVzBkTwH130wvj09tr4IC_gObsyqBaW_7DJTOucVM-nGjrufJGVSn6uzFppOcd8nK22UVnm1CA1T8SrEe2tLt2o4QURAnAKO)
# JS兼容性
## 常见问题和方案
# 通用的解决方法
# 参考

[学习CSS布局](http://zh.learnlayout.com/index.html)
